#!/usr/bin/env node
/**
 * render-canon.mjs — "one ledger, many renderings."
 * Generates CANON.md from the canonical registers and refreshes the generated
 * obligations block in README.md (between CANON:OBLIGATIONS markers). Run after
 * any register change:  node scripts/render-canon.mjs
 *
 * A document maintained as an independent source of truth is a future
 * contradiction — the registers in src/data/canon/ are the only source.
 */
import { writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const { STANDING, STANDING_ORDER } = await import(join(root, 'src/data/canon/standing.js'));
const { SYMBOLS } = await import(join(root, 'src/data/canon/symbols.js'));
const { NUMBERS } = await import(join(root, 'src/data/canon/numbers.js'));
const { CLAIMS } = await import(join(root, 'src/data/canon/claims.js'));
const { GATES } = await import(join(root, 'src/data/canon/gates.js'));
const { RETIREMENTS } = await import(join(root, 'src/data/canon/retirements.js'));
const { OBLIGATIONS } = await import(join(root, 'src/data/canon/obligations.js'));
const { runCanonValidation } = await import(join(root, 'src/simulation/CanonValidator.js'));

const v = runCanonValidation();
const esc = (s) => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');

// ---------- CANON.md ----------
let md = `# CANON — generated from \`src/data/canon/\`

> **Do not edit this file.** It is a rendering of the canonical registers
> (\`node scripts/render-canon.mjs\`). Edit the registers; regenerate.
> Validator: **${v.releasable ? 'RELEASABLE' : 'NOT RELEASABLE'}** — ${v.counts.blocking} blocking, ${v.counts.warning} listed.

## Definition of Done
${v.dod.map((d) => `- ${d.pass ? '✅' : '❌'} **DoD-${d.item}** — ${d.text}${d.note ? ` *(${d.note})*` : ''}`).join('\n')}

## Claim-standing ladder
| Standing | Meaning | Authority |
|---|---|---|
${STANDING_ORDER.map((k) => `| **${STANDING[k].label}** | ${esc(STANDING[k].meaning)} | ${esc(STANDING[k].authority)} |`).join('\n')}

## Claims (${CLAIMS.length})
| Claim | Standing | Scope | Falsifier | Artifact |
|---|---|---|---|---|
${CLAIMS.map((c) => `| ${esc(c.statement)} | ${c.standing} | ${esc(c.scope)} | ${esc(c.falsifier)} | \`${esc(c.artifact)}\` |`).join('\n')}

## Number cards (${NUMBERS.length})
| ID | Quantity | Value | Kind | Config | Uncertainty |
|---|---|---|---|---|---|
${NUMBERS.map((n) => `| \`${n.number_id}\` | ${esc(n.quantity)} | ${n.value} ${n.units} | ${n.kind}${n.derive ? ' ↻' : ''} | \`${n.configuration_id}\` | ${esc(n.uncertainty)} |`).join('\n')}

↻ = recomputed from stated inputs by the validator on every run.

## Symbol collision register (${SYMBOLS.length})
| Glyph | Conflict | Canonical names | In this repo |
|---|---|---|---|
${SYMBOLS.map((s) => `| ${s.glyph} | ${esc(s.conflict)} | ${s.canonical.map((c) => `\`${c}\``).join(', ')} | ${esc(s.usedInRepo)} |`).join('\n')}

## Gate contracts (${GATES.length})
| Gate | Invariant | Threshold | Provenance | Reason code |
|---|---|---|---|---|
${GATES.map((g) => `| ${esc(g.name)} | ${esc(g.invariant)} | ${esc(g.threshold.value)} | ${esc(g.threshold.provenance)} | \`${g.reasonCode}\` |`).join('\n')}

## Retirement register (${RETIREMENTS.length}) — removed, not owed
${RETIREMENTS.map((r) => `- **${esc(r.construct)}** — ${esc(r.reason)} *Disposition:* ${esc(r.disposition)}`).join('\n')}

## Open obligations (P0–P3)
| Pri | Obligation | Owner | Status | Absorbs |
|---|---|---|---|---|
${OBLIGATIONS.map((o) => `| ${o.priority} | ${esc(o.text)} | ${esc(o.owner)} | ${o.status} | ${o.absorbs.join(', ') || '—'} |`).join('\n')}

## Validator findings (${v.findings.length})
${v.findings.length === 0 ? '_None._' : v.findings.map((f) => `- **${f.severity.toUpperCase()}** \`${f.id}\` — ${esc(f.message)}`).join('\n')}
`;
writeFileSync(join(root, 'CANON.md'), md);
console.log(`CANON.md written (${md.length} chars). Releasable: ${v.releasable}`);

// ---------- README generated block ----------
const BEGIN = '<!-- CANON:OBLIGATIONS:BEGIN (generated by scripts/render-canon.mjs — do not edit) -->';
const END = '<!-- CANON:OBLIGATIONS:END -->';
const block = `${BEGIN}

The single obligations ledger lives in \`src/data/canon/obligations.js\` (rendered live in the
**Canon &amp; Integrity** view and in [\`CANON.md\`](./CANON.md)); it absorbs the earlier O-1…O-11 and
Void-Map V-1…V-4 lists. Current state — generated, not hand-maintained:

| Pri | Obligation | Status |
|---|---|---|
${OBLIGATIONS.map((o) => `| ${o.priority} | ${esc(o.text)} | ${o.status} |`).join('\n')}

${END}`;

const readmePath = join(root, 'README.md');
let readme = readFileSync(readmePath, 'utf8');
if (readme.includes(BEGIN)) {
  readme = readme.replace(new RegExp(`${BEGIN.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`), block);
  writeFileSync(readmePath, readme);
  console.log('README generated block refreshed.');
} else {
  console.log('README has no CANON:OBLIGATIONS markers yet — add them where the block should render.');
}
